apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    nginx.org/redirect-to-https: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: app.34.51.184.11.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: shipy-svc
            port:
              number: 80
