apiVersion: v1
kind: Service
metadata:
  name: shipy-svc
spec:
  type: ClusterIP #tak te≈º daje domyslnie
  ports:
  - port: 80
    targetPort: 7000
  selector:
    name: shipy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipy-deploy
spec:
  replicas: 3
  selector: 
    matchLabels:
      name: shipy
  template:
    metadata:
      labels:
        name: shipy
    spec:
      containers:
      - name: webapp-ctr
        image: k8smaestro/shipy-webapp:1.41.5
        ports:
        - containerPort: 7000